const ORDER_STATUS = {
  PLACED: 'placed',
  CONFIRMED: 'confirmed',
  PROCESSING: 'processing',
  SHIPPED: 'shipped',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
  RETURNED: 'returned',
  REFUNDED: 'refunded',
};

const PAYMENT_STATUS = {
  PENDING: 'pending',
  PAID: 'paid',
  FAILED: 'failed',
  REFUNDED: 'refunded',
  PARTIALLY_REFUNDED: 'partially_refunded',
};

const FULFILLMENT_STATUS = {
  PENDING: 'pending',
  MANUAL_ACTION_REQUIRED: 'manual_action_required',
  SUPPLIER_ORDERED: 'supplier_ordered',
  PROCESSING: 'processing',
  SHIPPED: 'shipped',
  DELIVERED: 'delivered',
  FAILED: 'failed',
};

const RETURN_STATUS = {
  RETURN_REQUESTED: 'return_requested',
  RETURN_APPROVED: 'return_approved',
  RETURN_REJECTED: 'return_rejected',
  RETURN_IN_TRANSIT: 'return_in_transit',
  RETURN_RECEIVED: 'return_received',
  REFUND_PENDING: 'refund_pending',
  REFUND_COMPLETED: 'refund_completed',
};

const ADMIN_ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  ORDER_MANAGER: 'order_manager',
  PRODUCT_MANAGER: 'product_manager',
  CONTENT_MANAGER: 'content_manager',
  SUPPORT_AGENT: 'support_agent',
};

const PERMISSIONS = {
  MANAGE_PRODUCTS: 'manage_products',
  MANAGE_CATEGORIES: 'manage_categories',
  MANAGE_ORDERS: 'manage_orders',
  MANAGE_CUSTOMERS: 'manage_customers',
  MANAGE_SUPPLIERS: 'manage_suppliers',
  MANAGE_SETTINGS: 'manage_settings',
  MANAGE_CONTENT: 'manage_content',
  MANAGE_COUPONS: 'manage_coupons',
  MANAGE_REVIEWS: 'manage_reviews',
  MANAGE_REFUNDS: 'manage_refunds',
  VIEW_REPORTS: 'view_reports',
  MANAGE_ADMIN_USERS: 'manage_admin_users',
};

const ROLE_PERMISSIONS = {
  [ADMIN_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ADMIN_ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ADMIN_ROLES.ORDER_MANAGER]: [
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_REFUNDS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ADMIN_ROLES.PRODUCT_MANAGER]: [
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ADMIN_ROLES.CONTENT_MANAGER]: [
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.MANAGE_REVIEWS,
  ],
  [ADMIN_ROLES.SUPPORT_AGENT]: [
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.MANAGE_CUSTOMERS,
  ],
};

const SUPPLIER_TYPES = {
  MANUAL_MARKETPLACE: 'manual_marketplace',
  MANUAL_DIRECT: 'manual_direct',
  API_MEESHO: 'api_meesho',
  API_SHIPROCKET: 'api_shiprocket',
  API_CUSTOM: 'api_custom',
};

const INTEGRATION_TYPES = {
  MANUAL: 'manual',
  API: 'api',
};

const PRODUCT_STATUS = {
  DRAFT: 'draft',
  ACTIVE: 'active',
  ARCHIVED: 'archived',
};

const COUPON_TYPES = {
  FIXED: 'fixed',
  PERCENTAGE: 'percentage',
  FREE_SHIPPING: 'free_shipping',
};

const REVIEW_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
};

const PAYMENT_METHODS = {
  RAZORPAY: 'razorpay',
  COD: 'cod',
};

const ORDER_STATUS_HISTORY_SOURCES = {
  ADMIN: 'admin',
  CUSTOMER: 'customer',
  PAYMENT_WEBHOOK: 'payment_webhook',
  SUPPLIER_API: 'supplier_api',
  SHIPPING_WEBHOOK: 'shipping_webhook',
  SYSTEM: 'system',
};

const AUDIT_ACTIONS = {
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  SUPPLIER_ORDER_CREATED: 'SUPPLIER_ORDER_CREATED',
  TRACKING_UPDATED: 'TRACKING_UPDATED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  ADMIN_USER_CREATED: 'ADMIN_USER_CREATED',
  ADMIN_USER_UPDATED: 'ADMIN_USER_UPDATED',
  REFUND_CREATED: 'REFUND_CREATED',
  COUPON_CREATED: 'COUPON_CREATED',
  REVIEW_UPDATED: 'REVIEW_UPDATED',
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
};

const WEBHOOK_STATUS = {
  RECEIVED: 'received',
  PROCESSING: 'processing',
  PROCESSED: 'processed',
  FAILED: 'failed',
  SKIPPED: 'skipped',
};

const STORAGE_PROVIDERS = {
  LOCAL: 'local',
  S3: 's3',
  GCS: 'gcs',
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  SUPPLIER_ORDER_FAILED: 'SUPPLIER_ORDER_FAILED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  WEBHOOK_INVALID: 'WEBHOOK_INVALID',
};

const CURRENCIES = {
  INR: { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  USD: { code: 'USD', symbol: '$', name: 'US Dollar' },
};

const DEFAULT_PAGE_SIZE = 20;
const MAX_PAGE_SIZE = 100;

module.exports = {
  ORDER_STATUS,
  PAYMENT_STATUS,
  FULFILLMENT_STATUS,
  RETURN_STATUS,
  ADMIN_ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  SUPPLIER_TYPES,
  INTEGRATION_TYPES,
  PRODUCT_STATUS,
  COUPON_TYPES,
  REVIEW_STATUS,
  PAYMENT_METHODS,
  ORDER_STATUS_HISTORY_SOURCES,
  AUDIT_ACTIONS,
  WEBHOOK_STATUS,
  STORAGE_PROVIDERS,
  HTTP_STATUS,
  ERROR_CODES,
  CURRENCIES,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
};
